// import { Geist, Geist_Mono } from "next/font/google";
import "@/app/globals.css";
import "@fortawesome/fontawesome-free/css/all.min.css"
import Header from "@/component/header";
import Footer from "@/component/footer";
import { cookies } from "next/headers";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const cookieStore = await cookies();
  const error = cookieStore.get("error")?.value;

  return (
    <html lang="en">
      <body
      // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header />
        {error && (
          <p className="p-2 bg-error rounded text-white">{error}</p>
        )}
        {children}
        <Footer />
      </body>
    </html>
  );
}
